### ISSUE TITLE
update whitepaper/website to reflect protocol improvements

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13257]
### Describe the feature request

With https://github.com/taikoxyz/taiko-mono/pull/13254/files, the protocol design is slightly different from the whitepaper. We should make sure the whitepaper captures most of the changes.

---

### Major Changes:
- [x] remove commit-and-propose scheme
- [x] txListProof must be part of the block proposal but it is not verified when a block is proposed. The main zk-proof must also include the txListProof circuit. Note that **txListProof doesn't verify transaction signatures are valid, it only verifies the block is decodable into a list of transactions, the byte size and number of transactions are within limits. Transactions with invalid signatures will be treated as those with incorrect nonce or insufficient ETH balance and will be dropped by L2 clients.**
- [x] invalid blocks are proven by running the zk-verifier for block's txListProofs and such verification must fail (invalidatedBlock function is deleted from TaikoL2.sol)
- [x] the anchor transaction validation is deleted from L1 and shall be done by a new circuit on top of the existing ZKP.
- [x] synchronize not only the block header hashes across chains, but also the SignalServcie Storage Roots (signalRoot) -- Currently to prove signal's validity on the destination chain, we need to provide a full merkle proof which has two parts, the account proof and the storage proof.  After this change, the account proof will be done only once in circuits. Users only need to provide the storage merkle proof, which will be less expensive.
