### ISSUE TITLE
feat(bridge-ui): tracking claim transactions

### ISSUE THREAD

**Issue by shadab-taiko** [taikoxyz/taiko-mono#13288]
- [x] Track claim transaction on the relayer
- [x] Add claim transaction to relayer's events API - #13289 
- [ ] Track claim transaction in Browser's localStorage
- [ ] Display claim transaction in Bridge-ui

**Comment by d1onys1us** [comment]
any status update on this @jscriptcoder ?

**Comment by jscriptcoder** [comment]
I'll create tickets for each of the remaining tasks. I'll close this soon
