### ISSUE TITLE
Clients supports the new protocol features

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13667]
- [x] ETH Deposits
- [x] Tokenomics? Do we need to do anything special
- [ ] Prepare and review protocol configurations (L2 & L3)
- [x] EIPs in Hardforks we need to enable and make sure we review those EIPs

**Comment by dantaik** [comment]
@davidtaikocha @cyberhorsey Feel free to split this into smaller issues if that makes sense.

**Comment by cyberhorsey** [comment]
PR is open for the last bit for ETH Deposits in taiko-geth.  
PR already merged in for the new feature "proofSkip" in taiko-client.  
Unsure what EIPs for hardforks entails.  
New tokenomics I don't think requires any changes from geth or client, I think just status page updates.

**Comment by d1onys1us** [comment]
i will close this issue now, however, if there is any remaining items for alpha-3 @davidtaikocha @cyberhorsey we can open up a new smaller issue or re-open this. thanks
