### ISSUE TITLE
Prepare for ETHPrague

### ISSUE THREAD

**Issue by umededoteth** [taikoxyz/taiko-mono#13714]
## ETHPrague tracking issue

Need to do some preparation for ETHPrague, including:

- [ ] Banner. -> @d1onys1us and @je4nt0nic 
- [ ] T-shirts. -> @je4nt0nic 
- [ ] Flyers (with protocol overview and building guide). -> @d1onys1us and @je4nt0nic 
- [ ] Stickers. -> @d1onys1us and @je4nt0nic 

Add whatever else needed to be done.
