### ISSUE TITLE
chore(docs): get ready for smart contract auditing

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#14545]
### Describe the feature request

Here is a list of things we need to finish:

- [x] Update Bridge related developer docs on our website.
- [x] Go over https://secure-contracts.com/ and [OZ's checklist](https://fs.hubspotusercontent00.net/hubfs/7795250/OZ_Audit_Readiness.pdf)
- [x] Internal review of all comments for Bridge and Vaults (focus on real comments inside the code, not the doc comments please)
- [x] Resolve all security vulnerabilities in repo stated by github
- [ ] Upgrade to latest patch version of solidity compiler
- [x] Translate https://github.com/taikoxyz/taiko-mono/blob/main/packages/protocol/docs/how_taiko_proves_blocks.md to Taiko website
- [ ] Add additional tests - https://github.com/taikoxyz/taiko-mono/issues/14979
- [ ] Review OZ source code used by our contract - do not assume!
### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by magicsat** [comment]
good

**Comment by alexandermacedonian** [comment]
wish you all the best

**Comment by traiderrr** [comment]
GOOD PROJECT LEST GO LAUNCH GUYS

**Comment by krypTuknife** [comment]
alpha 6 is coming!
