### ISSUE TITLE
Add additional solidity tests

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#14979]
### Describe the feature request

The test coverage report generated by `pnpm test:coverage` shows a lack of test coverage. (TaikoL1's coverage is almost zero as foundry doesn't support Library test coverage, we need to figure out the actual coverage later).

The test coverage report indicates we need to add more tests to test the following:

### High priority
- [x] *SignalService.sol*: the `proveSignalReceived` function needs more tests to coverage the for-loop. This will coverage the `verifyInclusionProof` function in *LibSecureMerkleTrie.sol*.
- [ ] *TaikoL2.sol*: the `_rewardParentBlock` function should be tested more thoroughly. There are quite a few if-else statements. Same with the `_calc1559BaseFee` function which will also coverage *Lib1559.sol* -- the file's coverage is also zero.
- [ ] *BridgedERC1155.sol* and *BridgedERC721.sol*has no coverage. *BridgedERC20.sol* also has no coverage, which is surprising.
- [ ] *XxxVault.sol*: all vaults also has no coverage, this is also surprising.
- [x] *Bridge.sol*: should add a test for `recallMessage`; we should also add a test to send a message whose `to` value is 0x0 or the bridge address on the destination chain.

### Low priority

- [ ] In many tests, the `init` functions are not covered. Need to figure out what caused it. *TaikoToken.sol*, and *TaikoL2.sol* are among those files.
- [ ] *GuardianProver.sol* has zero test coverage.
- [ ] *TaikoA6TierProvider.sol* has zero test coverage, we should add a very simple test for it.
- [ ] *L1/verifiers/Xxx.sol*: all verifiers have zero test coverage.

**Comment by adaki2004** [comment]
As per discussed, most of the 0% coverage is due to `forge coverage` issues. Will try to incorporate more tests tho, will check manually each what could be missing.
